### ISSUE TITLE
Transfer the repository ownership

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/popuko#235]
This application is used in [voyagegroup](https://github.com/voyagegroup) extremely, and I and @nekoya develop this in our working time, and some budgets for infrastructure is provided by the company. So I think we should transfer the ownership of this repository to

-  [voyagegroup](https://github.com/voyagegroup)
- Or other new organization like `popukobot`.

**Comment by saneyuki** [comment]
@nekoya how about do you think?

**Comment by nekoya** [comment]
I don't have strong opinion originally.

Today, popuko has been becoming popular in our company than we thought at first. Thus I think `voyagegroup` is the most suitable organization.

And we can transfer to another organization if we hope it. Easy go.

**Comment by saneyuki** [comment]
I'll transfer to `voyagegroup`

**Comment by saneyuki** [comment]
I've updated links in [this article](http://techlog.voyagegroup.com/entry/2017/02/14/080000)
