### ISSUE TITLE
homu.io doesn't exist any more

### ISSUE THREAD

**Issue by notriddle** [voyagegroup/popuko#243]
The README still refers people to homu.io, which has been down for awhile.

Maybe you should refer to <https://bors.tech> instead? It's up, and it has more than one person committed to keeping the lights on.

**Comment by saneyuki** [comment]
@notriddle 

Thank you for your information! 

> Maybe you should refer to https://bors.tech instead? It's up, and it has more than one person committed to keeping the lights on.

Yeah. I agree with it
